name: Build and deploy Python app to Azure Web App - python-fastapi

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgl1-mesa-glx libglib2.0-0 libsm6 libxext6 libxrender-dev

      - name: Install YOLOv10
        run: |
          git clone https://github.com/THU-MIG/yolov10.git
          cd yolov10
          pip install -r requirements.txt
          pip install -e .
          cd ..

      - name: Install Python dependencies
        run: pip install -r requirements.txt


      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: |
            ./*
            !venv/
            !.git/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_1876CB2F103548508EABEE34097FC540 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_C8029B35F8214715807DB1B29D2208A7 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_EFD936B89DFB42DE9A190A600E24360F }}

      - name: Configure App Service settings
        uses: azure/appservice-settings@v1
        with:
          app-name: 'python-fastapi'
          app-settings-json: |
            [
              {
                "name": "SCM_DO_BUILD_DURING_DEPLOYMENT",
                "value": "true"
              },
              {
                "name": "WEBSITE_WEBDEPLOY_USE_SCM",
                "value": "true"
              }
            ]

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'python-fastapi'
          slot-name: 'Production'
          startup-command: 'gunicorn --bind=0.0.0.0 --timeout 600 --workers 4 --worker-class uvicorn.workers.UvicornWorker main:app'
